### ISSUE TITLE
Some Transaction check error occured

### ISSUE THREAD

**Issue by AQA6666** [NVIDIA/yum-packaging-fabric-manager#4]
when I run "yum install cuda-drivers-fabricmanager-470"
in my CentOS7.8 server
Transaction check error:
  file /usr/bin/nvidia-modprobe conflicts between attempted installs of nvidia-modprobe-3:495.29.05-1.el8.x86_64 and nvidia-modprobe-latest-3:495.29.05-1.el7.x86_64
  file /usr/bin/nvidia-persistenced conflicts between attempted installs of nvidia-persistenced-3:495.29.05-1.el8.x86_64 and nvidia-persistenced-latest-3:495.29.05-1.el7.x86_64
  file /usr/bin/nvidia-xconfig conflicts between attempted installs of nvidia-xconfig-3:495.29.05-1.el8.x86_64 and nvidia-xconfig-latest-3:495.29.05-1.el7.x86_64
It seemd that some "el8" conflict with some "el7"?why?

**Comment by AQA6666** [comment]
Dependencies Resolved

==========================================================================================================================================
 Package                                       Arch                Version                           Repository                      Size
==========================================================================================================================================
Installing:
 cuda-drivers-fabricmanager-470                x86_64              470.82.01-1                       cuda-rhel7-x86_64              3.3 k
Installing for dependencies:
 adwaita-cursor-theme                          noarch              3.28.0-1.el7                      base                           641 k
 adwaita-icon-theme                            noarch              3.28.0-1.el7                      base                            11 M
 at-spi2-atk                                   x86_64              2.26.2-1.el7                      base                            81 k
 at-spi2-core                                  x86_64              2.28.0-1.el7                      base                           158 k
 atk                                           x86_64              2.28.1-2.el7                      base                           263 k
 cairo                                         x86_64              1.15.12-4.el7                     base                           741 k
 cairo-gobject                                 x86_64              1.15.12-4.el7                     base                            26 k
 colord-libs                                   x86_64              1.3.4-2.el7                       base                           186 k
 cuda-drivers                                  x86_64              470.82.01-1                       cuda-rhel7-x86_64              3.6 k
 cups-libs                                     x86_64              1:1.6.3-51.el7                    base                           359 k
 dconf                                         x86_64              0.28.0-4.el7                      base                           106 k
 dejavu-fonts-common                           noarch              2.33-6.el7                        base                            64 k
 dejavu-sans-fonts                             noarch              2.33-6.el7                        base                           1.4 M
 dkms                                          noarch              3.0.3-1.el7                       epel                            59 k
 fontconfig                                    x86_64              2.13.0-4.3.el7                    base                           254 k
 fontpackages-filesystem                       noarch              1.44-8.el7                        base                           9.9 k
 fribidi                                       x86_64              1.0.2-1.el7_7.1                   base                            79 k
 gdk-pixbuf2                                   x86_64              2.36.12-3.el7                     base                           570 k
 glib-networking                               x86_64              2.56.1-1.el7                      base                           145 k
 graphite2                                     x86_64              1.3.10-1.el7_3                    base                           115 k
 gsettings-desktop-schemas                     x86_64              3.28.0-3.el7                      base                           606 k
 gtk-update-icon-cache                         x86_64              3.22.30-6.el7                     updates                         27 k
 gtk3                                          x86_64              3.22.30-6.el7                     updates                        4.4 M
 harfbuzz                                      x86_64              1.7.5-2.el7                       base                           267 k
 hicolor-icon-theme                            noarch              0.12-7.el7                        base                            42 k
 jasper-libs                                   x86_64              1.900.1-33.el7                    base                           150 k
 jbigkit-libs                                  x86_64              2.0-11.el7                        base                            46 k
 json-glib                                     x86_64              1.4.2-2.el7                       base                           134 k
 kmod-nvidia-latest-dkms                       x86_64              3:495.29.05-1.el8                 cuda-rhel8-x86_64               27 M
 lcms2                                         x86_64              2.6-3.el7                         base                           150 k
 libX11-devel                                  x86_64              1.6.7-4.el7_9                     updates                        981 k
 libXau-devel                                  x86_64              1.0.8-2.1.el7                     base                            14 k
 libXcomposite                                 x86_64              0.4.4-4.1.el7                     base                            22 k
 libXcursor                                    x86_64              1.1.15-1.el7                      base                            30 k
 libXdmcp                                      x86_64              1.1.2-6.el7                       base                            34 k
 libXfont2                                     x86_64              2.0.3-1.el7                       base                           143 k
 libXft                                        x86_64              2.3.2-2.el7                       base                            58 k
 libXi                                         x86_64              1.7.9-1.el7                       base                            40 k
 libXinerama                                   x86_64              1.1.3-2.1.el7                     base                            14 k
 libXrandr                                     x86_64              1.5.1-2.el7                       base                            27 k
 libXrender                                    x86_64              0.9.10-1.el7                      base                            26 k
 libXtst                                       x86_64              1.2.3-1.el7                       base                            20 k
 libepoxy                                      x86_64              1.5.2-1.el7                       base                           211 k
 libfontenc                                    x86_64              1.1.3-3.el7                       base                            31 k
 libgusb                                       x86_64              0.2.9-1.el7                       base                            40 k
 libjpeg-turbo                                 x86_64              1.2.90-8.el7                      base                           135 k
 libsoup                                       x86_64              2.62.2-2.el7                      base                           411 k
 libthai                                       x86_64              0.1.14-9.el7                      base                           187 k
 libtiff                                       x86_64              4.0.3-35.el7                      base                           172 k
 libusbx                                       x86_64              1.0.21-1.el7                      base                            61 k
 libvdpau                                      x86_64              1.1.1-3.el7                       base                            34 k
 libwayland-cursor                             x86_64              1.15.0-1.el7                      base                            20 k
 libwayland-egl                                x86_64              1.15.0-1.el7                      base                            13 k
 libxcb-devel                                  x86_64              1.13-1.el7                        base                           1.1 M
 libxkbcommon                                  x86_64              0.7.1-3.el7                       base                           108 k
 libxkbfile                                    x86_64              1.0.9-3.el7                       base                            83 k
 nvidia-driver-latest                          x86_64              3:495.29.05-1.el7                 cuda-rhel7-x86_64               21 M
 nvidia-driver-latest-NVML                     x86_64              3:495.29.05-1.el7                 cuda-rhel7-x86_64              516 k
 nvidia-driver-latest-NvFBCOpenGL              x86_64              3:495.29.05-1.el7                 cuda-rhel7-x86_64               59 k
 nvidia-driver-latest-cuda                     x86_64              3:495.29.05-1.el7                 cuda-rhel7-x86_64              338 k
 nvidia-driver-latest-cuda-libs                x86_64              3:495.29.05-1.el7                 cuda-rhel7-x86_64               37 M
 nvidia-driver-latest-devel                    x86_64              3:495.29.05-1.el7                 cuda-rhel7-x86_64               19 k
 nvidia-driver-latest-libs                     x86_64              3:495.29.05-1.el7                 cuda-rhel7-x86_64              148 M
 nvidia-fabric-manager                         x86_64              470.82.01-1                       cuda-rhel7-x86_64              1.1 M
 nvidia-libXNVCtrl                             x86_64              3:495.29.05-1.el8                 cuda-rhel8-x86_64               24 k
 nvidia-libXNVCtrl-devel                       x86_64              3:495.29.05-1.el8                 cuda-rhel8-x86_64               55 k
 nvidia-modprobe                               x86_64              3:495.29.05-1.el8                 cuda-rhel8-x86_64               36 k
 nvidia-modprobe-latest                        x86_64              3:495.29.05-1.el7                 cuda-rhel7-x86_64               34 k
 nvidia-persistenced                           x86_64              3:495.29.05-1.el8                 cuda-rhel8-x86_64               42 k
 nvidia-persistenced-latest                    x86_64              3:495.29.05-1.el7                 cuda-rhel7-x86_64               36 k
 nvidia-settings                               x86_64              3:495.29.05-1.el8                 cuda-rhel8-x86_64              826 k
 nvidia-xconfig                                x86_64              3:495.29.05-1.el8                 cuda-rhel8-x86_64              104 k
 nvidia-xconfig-latest                         x86_64              3:495.29.05-1.el7                 cuda-rhel7-x86_64               94 k
 ocl-icd                                       x86_64              2.2.12-1.el7                      epel                            43 k
 opencl-filesystem                             noarch              1.0-5.el7                         epel                           3.9 k
 pango                                         x86_64              1.42.4-4.el7_7                    base                           280 k
 pixman                                        x86_64              0.34.0-1.el7                      base                           248 k
 rest                                          x86_64              0.8.1-2.el7                       base                            63 k
 vulkan-filesystem                             noarch              1.1.97.0-1.el7                    base                           6.3 k
 xkeyboard-config                              noarch              2.24-1.el7                        base                           834 k
 xorg-x11-proto-devel                          noarch              2018.4-1.el7                      base                           280 k
 xorg-x11-server-Xorg                          x86_64              1.20.4-17.el7_9                   updates                        1.5 M
 xorg-x11-server-common                        x86_64              1.20.4-17.el7_9                   updates                         56 k
 xorg-x11-xkb-utils                            x86_64              7.7-14.el7                        base                           103 k
 yum-plugin-nvidia                             noarch              0.5-1.el7                         cuda-rhel7-x86_64              9.9 k

**Comment by AQA6666** [comment]
Install  1 Package (+85 Dependent packages)

Total size: 265 M
Total download size: 239 M
Installed size: 669 M
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for cuda-rhel8-x86_64
No Presto metadata available for cuda-rhel7-x86_64
(1/32): cuda-drivers-470.82.01-1.x86_64.rpm                                                                        | 3.6 kB  00:00:01     
(2/32): cuda-drivers-fabricmanager-470-470.82.01-1.x86_64.rpm                                                      | 3.3 kB  00:00:02     
(3/32): kmod-nvidia-latest-dkms-495.29.05-1.el8.x86_64.rpm                                                         |  27 MB  00:00:02     
(4/32): nvidia-driver-latest-NVML-495.29.05-1.el7.x86_64.rpm                                                       | 516 kB  00:00:01     
(5/32): nvidia-driver-latest-NvFBCOpenGL-495.29.05-1.el7.x86_64.rpm                                                |  59 kB  00:00:00     
(6/32): nvidia-driver-latest-495.29.05-1.el7.x86_64.rpm                                                            |  21 MB  00:00:02     
(7/32): nvidia-driver-latest-cuda-495.29.05-1.el7.x86_64.rpm                                                       | 338 kB  00:00:00     
(8/32): nvidia-driver-latest-devel-495.29.05-1.el7.x86_64.rpm                                                      |  19 kB  00:00:00     
(9/32): nvidia-driver-latest-cuda-libs-495.29.05-1.el7.x86_64.rpm                                                  |  37 MB  00:00:07     
(10/32): nvidia-fabric-manager-470.82.01-1.x86_64.rpm                                                              | 1.1 MB  00:00:00     
(11/32): nvidia-libXNVCtrl-devel-495.29.05-1.el8.x86_64.rpm                                                        |  55 kB  00:00:02     
(12/32): nvidia-libXNVCtrl-495.29.05-1.el8.x86_64.rpm                                                              |  24 kB  00:00:04     
(13/32): nvidia-modprobe-495.29.05-1.el8.x86_64.rpm                                                                |  36 kB  00:00:01     
(14/32): nvidia-persistenced-495.29.05-1.el8.x86_64.rpm                                                            |  42 kB  00:00:00     
(15/32): nvidia-modprobe-latest-495.29.05-1.el7.x86_64.rpm                                                         |  34 kB  00:00:11     
(16/32): nvidia-persistenced-latest-495.29.05-1.el7.x86_64.rpm                                                     |  36 kB  00:00:00     
(17/32): ocl-icd-2.2.12-1.el7.x86_64.rpm                                                                           |  43 kB  00:00:00     
(18/32): nvidia-xconfig-latest-495.29.05-1.el7.x86_64.rpm                                                          |  94 kB  00:00:00     
(19/32): opencl-filesystem-1.0-5.el7.noarch.rpm                                                                    | 3.9 kB  00:00:00     
(20/32): nvidia-settings-495.29.05-1.el8.x86_64.rpm                                                                | 826 kB  00:00:03     
(21/32): pixman-0.34.0-1.el7.x86_64.rpm                                                                            | 248 kB  00:00:02     
(22/32): pango-1.42.4-4.el7_7.x86_64.rpm                                                                           | 280 kB  00:00:03     
(23/32): rest-0.8.1-2.el7.x86_64.rpm                                                                               |  63 kB  00:00:00     
(24/32): vulkan-filesystem-1.1.97.0-1.el7.noarch.rpm                                                               | 6.3 kB  00:00:00     
(25/32): nvidia-driver-latest-libs-495.29.05-1.el7.x86_64.rpm                                                      | 148 MB  00:00:26     
(26/32): xkeyboard-config-2.24-1.el7.noarch.rpm                                                                    | 834 kB  00:00:00     
(27/32): xorg-x11-proto-devel-2018.4-1.el7.noarch.rpm                                                              | 280 kB  00:00:00     
(28/32): xorg-x11-xkb-utils-7.7-14.el7.x86_64.rpm                                                                  | 103 kB  00:00:00     
(29/32): xorg-x11-server-Xorg-1.20.4-17.el7_9.x86_64.rpm                                                           | 1.5 MB  00:00:00     
(30/32): xorg-x11-server-common-1.20.4-17.el7_9.x86_64.rpm                                                         |  56 kB  00:00:00     
(31/32): yum-plugin-nvidia-0.5-1.el7.noarch.rpm                                                                    | 9.9 kB  00:00:00     
(32/32): nvidia-xconfig-495.29.05-1.el8.x86_64.rpm                                                                 | 104 kB  00:00:07

**Comment by AQA6666** [comment]
I solved this problem by remove cuda repo for rhel8 in yum, which was added to yum uncarefully.

**Comment by kmittman** [comment]
Yup, the cuda repos are distro/arch specific.

RHEL7 instructions are posted here:
https://github.com/NVIDIA/yum-packaging-fabric-manager/issues/1#issuecomment-884424277
